[package]
name = "fusegu"
version = "0.1.0"
edition = "2024"
license = "AGPL-3.0-only"
repository = "https://github.com/fusegu-dev/fusegu"
homepage = "https://fusegu.dev"

[dependencies]

[profile.dev]
debug = true

[profile.test]
opt-level = 1