name: Feature Request
description: Suggest a new feature for Fusegu
labels: ["enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting a new feature!

  - type: textarea
    id: feature-description
    attributes:
      label: Feature description
      description: What feature would you like to see added?
      placeholder: Describe the feature you'd like
    validations:
      required: true

  - type: textarea
    id: use-case
    attributes:
      label: Use case
      description: Why would this feature be useful? What problem does it solve?
      placeholder: Explain how this would help with fraud detection/prevention
    validations:
      required: true

  - type: textarea
    id: additional-context
    attributes:
      label: Additional context
      description: Add any other context, screenshots, or examples about the feature request