name: "Pull Request Labeler"

on:
  pull_request_target:
    types: [opened, synchronize, reopened, edited]

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.sha }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  triage:
    name: Label PR
    permissions:
      contents: read # for actions/labeler to determine modified files
      pull-requests: write # for actions/labeler to add labels to PRs
    runs-on: ubuntu-latest
    # Only run on PRs from forks or main repo (skip draft PRs to save resources)
    if: github.event.pull_request.draft == false
    steps:
      - name: Apply labels
        uses: actions/labeler@v5
        with:
          repo-token: "${{ secrets.GITHUB_TOKEN }}"
          sync-labels: true
          dot: true # Support .file paths in labeler.yml
